### PR TITLE
change task color to black to improve readability

### PR DESCRIPTION
**Pull request by mohsenkhosroanjam**
Isssue #20

### CODE REVIEW

**Review by BDadmehr0 — CHANGES_REQUESTED** [review]
please delete .idea file in project dirctory

**Comment by mohsenkhosroanjam** [comment]
Done.

**Comment by BDadmehr0** [comment]
If the text turns black in the white theme, logically, it should turn white in the black theme. What do you think?

``` python
"Dark": {
                "Pending": {
                    "background": QtGui.QColor(66, 66, 66),
                    "foreground": QtGui.QColor("white"), 
                },
                "Completed": {
                    "background": QtGui.QColor(34, 139, 34),  # Dark green
                    "foreground": QtGui.QColor("white"),
                },
            },
        }
```

**Comment by mohsenkhosroanjam** [comment]
I thought the readability in dark mode was ok, so I did not make any changes to it. I did not think about the logic, I just considered the end user. Should I change it to white? 
I can change and test it to see whether it improves the readability in dark mode too.

**Comment by BDadmehr0** [comment]
> I thought the readability in dark mode was ok, so I did not make any changes to it. I did not think about the logic, I just considered the end user. Should I change it to white? I can change and test it to see whether it improves the readability in dark mode too.

Whatever works best for you; it was just a suggestion.

**Comment by BDadmehr0** [comment]
But I feel the colors are too starkly white and black. We could have used RGB colors to create slightly softer shades of white and black. @mohsenkhosroanjam 

ex : rgb(51, 51, 51) #gray

**Comment by mohsenkhosroanjam** [comment]
I tested it with gray. Gray would not be bad in light mode but not good in dark mode. Shall we use "darkslategray" in light mode and white in dark mode? I tested it, seems perfect.
image
image

**Comment by BDadmehr0** [comment]
> I tested it with gray. Gray would not be bad in light mode but not good in dark mode. Shall we use "darkslategray" in light mode and white in dark mode? I tested it, seems perfect. image image

If the changes are like the picture, that's perfect; we can merge them.

**Comment by mohsenkhosroanjam** [comment]
I Just committed and pushed the above changes.

**Review by BDadmehr0 — APPROVED** [review]

**Comment by BDadmehr0** [comment]
Thank you for the improvements! The changes look great, and I appreciate your attention to detail. Let's go ahead and merge!

**Pull request merged**
